global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "mini-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8000"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

